services:
  - type: web
    name: discord-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class eventlet -w 1 main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
