services:
  - type: web
    name: discord-bot
    env: python
    pythonVersion: 3.11  # Forzamos Python 3.11
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: false
